application: moneydog-tw
version: 2.0208
runtime: python
api_version: 1

handlers:

- url: /templates
  script: index.py

- url: /css
  static_dir: css
  
- url: /js
  static_dir: js

- url: /img
  static_dir: img

- url: /test
  script: test.py  
  
- url: .*
  script: index.py
